// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/template/template.proto

package template

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Templates service

type TemplatesService interface {
	// 获取权限列表
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取模板
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 创建模板
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 更新模板
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 删除模板
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type templatesService struct {
	c    client.Client
	name string
}

func NewTemplatesService(name string, c client.Client) TemplatesService {
	return &templatesService{
		c:    c,
		name: name,
	}
}

func (c *templatesService) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Templates.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Templates.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesService) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Templates.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesService) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Templates.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesService) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Templates.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Templates service

type TemplatesHandler interface {
	// 获取权限列表
	List(context.Context, *Request, *Response) error
	// 根据 唯一 获取模板
	Get(context.Context, *Request, *Response) error
	// 创建模板
	Create(context.Context, *Request, *Response) error
	// 更新模板
	Update(context.Context, *Request, *Response) error
	// 删除模板
	Delete(context.Context, *Request, *Response) error
}

func RegisterTemplatesHandler(s server.Server, hdlr TemplatesHandler, opts ...server.HandlerOption) error {
	type templates interface {
		List(ctx context.Context, in *Request, out *Response) error
		Get(ctx context.Context, in *Request, out *Response) error
		Create(ctx context.Context, in *Request, out *Response) error
		Update(ctx context.Context, in *Request, out *Response) error
		Delete(ctx context.Context, in *Request, out *Response) error
	}
	type Templates struct {
		templates
	}
	h := &templatesHandler{hdlr}
	return s.Handle(s.NewHandler(&Templates{h}, opts...))
}

type templatesHandler struct {
	TemplatesHandler
}

func (h *templatesHandler) List(ctx context.Context, in *Request, out *Response) error {
	return h.TemplatesHandler.List(ctx, in, out)
}

func (h *templatesHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.TemplatesHandler.Get(ctx, in, out)
}

func (h *templatesHandler) Create(ctx context.Context, in *Request, out *Response) error {
	return h.TemplatesHandler.Create(ctx, in, out)
}

func (h *templatesHandler) Update(ctx context.Context, in *Request, out *Response) error {
	return h.TemplatesHandler.Update(ctx, in, out)
}

func (h *templatesHandler) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.TemplatesHandler.Delete(ctx, in, out)
}
